### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by zachgibson** [viktorstrate/swift-tree-sitter#44]
Hello I was just wondering how I could do syntax highlighting with this lib?

**Comment by viktorstrate** [comment]
I've made a small text editor that is very unfinished but it might be a good source of inspiration.

Take a look at the `updateTextHighlight()` function as a starting point:

https://github.com/viktorstrate/Bonsai/blob/ac78513eb53d9754833966205c982cf8f63fbbb9/Bonsai/Views/Code/SyntaxTreeAnalysis/CodeSyntaxTree.swift#L183-L207

**Comment by zachgibson** [comment]
Ok thanks I will check that out.

**Comment by zachgibson** [comment]
I got it to work. Thanks again. 🙂
